import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, Bell, CalendarDays, Check, Sparkles } from "lucide-react";
import { toast } from "sonner";
import beforeImage from "@/assets/pmu-before.jpg";
import afterImage from "@/assets/pmu-after.jpg";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { BeforeAfterSlider, Chip, EmptyState, StatTile, StudioBadge, UnreadAvatar } from "@/components/studio-funnel";

export const Route = createFileRoute("/styleguide")({
  head: () => ({ meta: [{ title: "Style Guide — Studio Funnel" }, { name: "description", content: "The visual language and reusable interface components for Studio Funnel." }, { property: "og:title", content: "Studio Funnel Style Guide" }, { property: "og:description", content: "A polished component reference for the Studio Funnel experience." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: StyleGuide,
});

const Section = ({ number, title, children }: { number: string; title: string; children: React.ReactNode }) => <section className="grid gap-6 border-t py-12 lg:grid-cols-[220px_1fr] lg:py-16"><div><p className="text-xs font-bold text-primary">{number}</p><h2 className="mt-2 text-2xl">{title}</h2></div><div>{children}</div></section>;

function StyleGuide() {
  const [selected, setSelected] = useState("Brows");
  return <main className="min-h-screen px-5 pb-20 sm:px-10"><header className="mx-auto flex min-h-20 max-w-6xl items-center justify-between border-b"><a href="/" className="font-display text-xl">Studio Funnel</a><div className="flex items-center gap-3"><span className="hidden text-xs font-bold uppercase text-muted-foreground sm:block">Design system · v1.0</span><UnreadAvatar initials="SC" /></div></header>
    <div className="mx-auto max-w-6xl"><div className="grid gap-10 py-16 md:grid-cols-[1.35fr_.65fr] md:items-end md:py-24"><div><p className="mb-5 text-xs font-bold uppercase text-primary">The foundation</p><h1 className="max-w-4xl text-5xl leading-[1.02] sm:text-7xl">Calm confidence,<br/><em className="font-normal text-primary">beautifully organised.</em></h1></div><p className="max-w-sm text-sm leading-7 text-muted-foreground">A warm, considered visual language for the intimate work of permanent makeup studios—never cold, never clinical.</p></div>
      <Section number="01" title="Colour"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Bone","bg-background"],["Sand","bg-secondary"],["Taupe","bg-muted-foreground"],["Mulberry","bg-primary"],["Sage","bg-success"],["Amber","bg-waiting"]].map(([name,color])=><div key={name}><div className={`aspect-square rounded-2xl border ${color}`}/><p className="mt-3 text-sm font-semibold">{name}</p></div>)}</div></Section>
      <Section number="02" title="Typography"><div className="space-y-8"><div><p className="text-xs font-bold uppercase text-muted-foreground">Display · Fraunces</p><p className="mt-3 font-display text-5xl leading-tight sm:text-6xl">Every detail, considered.</p></div><div><p className="text-xs font-bold uppercase text-muted-foreground">Interface · Manrope</p><p className="mt-3 max-w-2xl text-base leading-7">Warm, direct language makes studio management feel effortless and human.</p></div></div></Section>
      <Section number="03" title="Actions"><div className="flex flex-wrap gap-3"><Button>Book consultation <ArrowRight/></Button><Button variant="secondary">Save changes</Button><Button variant="quiet">Not now</Button><Button size="icon" aria-label="Notifications"><Bell/></Button></div></Section>
      <Section number="04" title="Selection & status"><div className="space-y-6"><div className="flex flex-wrap gap-2">{["Brows","Lips","Liner","Freckles"].map(x=><Chip key={x} selected={selected===x} onClick={()=>setSelected(x)}>{x}</Chip>)}</div><div className="flex flex-wrap gap-2"><StudioBadge tone="instagram">Instagram</StudioBadge><StudioBadge tone="meta">Meta</StudioBadge><StudioBadge tone="google">Google</StudioBadge><StudioBadge tone="direct">Direct</StudioBadge></div><div className="flex flex-wrap gap-2"><StudioBadge tone="new">New</StudioBadge><StudioBadge tone="contacted">Contacted</StudioBadge><StudioBadge tone="booked"><Check className="size-3"/> Booked</StudioBadge><StudioBadge tone="notInterested">Not interested</StudioBadge></div></div></Section>
      <Section number="05" title="Fields"><Card className="max-w-2xl"><CardHeader><CardTitle>Client details</CardTitle><CardDescription>A soft, focused form treatment.</CardDescription></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Full name<Input placeholder="Amelia Hart"/></label><label className="grid gap-2 text-sm font-semibold">Email<Input type="email" placeholder="amelia@example.com"/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Notes<Textarea placeholder="Add treatment preferences or context…"/></label><div className="flex min-h-12 items-center justify-between sm:col-span-2"><div><p className="text-sm font-semibold">Appointment reminders</p><p className="text-xs text-muted-foreground">Send a gentle reminder 24 hours before.</p></div><Switch defaultChecked aria-label="Appointment reminders"/></div></CardContent></Card></Section>
      <Section number="06" title="Cards & metrics"><div className="grid gap-4 sm:grid-cols-3"><StatTile label="New leads" value="24" change="↑ 18% this month"/><StatTile label="Booked" value="11" change="46% conversion"/><StatTile label="Revenue" value="£4.8k" change="↑ £820 this month"/></div></Section>
      <Section number="07" title="Transformation"><div className="max-w-3xl"><BeforeAfterSlider before={beforeImage} after={afterImage}/><p className="mt-4 text-xs leading-5 text-muted-foreground">Drag to compare · Powder brows, healed at six weeks</p></div></Section>
      <Section number="08" title="Feedback & overlays"><div className="grid gap-4 md:grid-cols-2"><Card><EmptyState/></Card><Card><CardHeader><CardTitle>Gentle confirmations</CardTitle><CardDescription>Keep feedback clear, quiet, and useful.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3"><Button variant="secondary" onClick={()=>toast.success("Lead marked as booked")}>Show toast <Sparkles/></Button><Sheet><SheetTrigger asChild><Button>Open bottom sheet</Button></SheetTrigger><SheetContent side="bottom" className="mx-auto max-w-2xl p-7"><SheetHeader><SheetTitle className="text-2xl">Schedule a consultation</SheetTitle><SheetDescription>Choose the best next step for this client.</SheetDescription></SheetHeader><div className="mt-6 grid gap-3 sm:grid-cols-2"><Button><CalendarDays/> Pick a time</Button><Button variant="secondary">Send booking link</Button></div></SheetContent></Sheet></CardContent></Card></div></Section>
    </div></main>;
}
